/**
 * Exporter Utility
 * Generates downloadable .param, .csv, and .json files for ArduPilot parameter sets.
 */

/**
 * Download text content as a file in browser
 */
export function downloadFile(content, filename, mimeType) {
	const blob = new Blob([content], { type: mimeType });
	const url = URL.createObjectURL(blob);
	const a = document.createElement("a");
	a.href = url;
	a.download = filename;
	document.body.appendChild(a);
	a.click();
	document.body.removeChild(a);
	URL.revokeObjectURL(url);
}

/**
 * Format parameter list to Mission Planner standard .param format
 */
export function generateParamFile(parameters, vehicleName, versionTag) {
	const header = `# ArduPilot Default Parameters Export
# Vehicle: ${vehicleName}
# Firmware Version: ${versionTag}
# Generated by ArduPilot Parameter Explorer
# Format: PARAM_NAME,VALUE
`;

	const lines = parameters.map((p) => `${p.name},${p.defaultValue}`);
	return `${header}${lines.join("\n")}\n`;
}

/**
 * Format parameter list to CSV format with full metadata
 */
export function generateCsvFile(parameters) {
	const header = [
		"Parameter Name",
		"Default Value",
		"Units",
		"Category",
		"Display Name",
		"Description",
	];

	const escapeCsv = (str) => {
		if (!str) return '""';
		const cleanStr = String(str).replace(/"/g, '""');
		return `"${cleanStr}"`;
	};

	const rows = parameters.map((p) =>
		[
			escapeCsv(p.name),
			escapeCsv(p.defaultValue),
			escapeCsv(p.units),
			escapeCsv(p.category),
			escapeCsv(p.displayName),
			escapeCsv(p.description),
		].join(","),
	);

	return [header.join(","), ...rows].join("\n");
}

/**
 * Export JSON file
 */
export function generateJsonFile(parameters, vehicleName, versionTag) {
	return JSON.stringify(
		{
			application: "ArduPilot Parameter Explorer",
			vehicle: vehicleName,
			firmwareVersion: versionTag,
			exportedAt: new Date().toISOString(),
			totalParameters: parameters.length,
			parameters: parameters,
		},
		null,
		2,
	);
}
